### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [patri9ck/a2ln-app#24]
Mlkit is not FOSS. Could you please take a look? Thanks!

**Comment by patri9ck** [comment]
Thank you. I will take a look at it.

**Comment by patri9ck** [comment]
Is there some way to take a look at the build log? For me, there is a 404 on https://monitor.f-droid.org/builds/log/dev.patri9ck.a2ln/7.

**Comment by linsui** [comment]
It hasn't been built in the buildserver. https://gitlab.com/fdroid/fdroiddata/-/jobs/2812112858

**Comment by patri9ck** [comment]
I see, thank you. Is there any way to exclude it from the Gradle build script when it is built by F-Droid but otherwise keep it?

**Comment by linsui** [comment]
You need to add a flavor without it.

**Comment by jonas-w** [comment]
How about "outsourcing" the qr code scanning?

So for example i could scan it with my camera app and then "opening" the qr code would redirect to the app with the correct parameters.

This would be a workaround for the non FOSS MlKit and also add some convinience.

I don't have much knowledge about Mobile Dev and don't know if this is more work than necessary.

**Comment by patri9ck** [comment]
I already created a fix which uses the fully open source library ZXing instead of any proprietary Google Play services. I will push my code and create a new release as soon as possible.

I also created [this F-Droid forum post](https://forum.f-droid.org/t/using-microg-instead-of-google-play-services-for-my-apl/19337/5) where I received very useful help.

**Comment by jonas-w** [comment]
Oh okay perfect!
